#!/bin/bash

# Configuración visual
bspc config normal_border_color "#333333"
bspc config focused_border_color "#5e0b0b"
bspc config window_gap 1

# Configurar escritorios solo cuando el monitor está disponible
bspc monitor -d I II III IV V VI VII VIII IX X

# Aplicaciones opcionales
# (sleep 1 && kitty) &
