#!/bin/bash

# Lanzar sxhkd (atajos de teclado)
pgrep -x sxhkd > /dev/null || sxhkd &

# Configuración de BSPWM
bspc config normal_border_color "#333333"
bspc config focused_border_color "#5e0b0b"
bspc config window_gap 1

# Definir escritorios
bspc monitor -d I II III IV V VI VII VIII IX X

# Iniciar aplicaciones luego de que el entorno esté listo
(sleep 1 && kitty) &
# (sleep 1 && ~/.config/polybar/launch.sh) &

