---
- name: Setup Development Environment
  hosts: localhost
  become: yes
  vars:
    tools_to_install:
      - basics
      - asdf
      - zsh
      - i3
      - rofi
      - polybar
      - kitty
      - tmux
      - neovim
      - timewarrior
      - dotfiles

  tasks:
    - name: Install basic tools
      apt:
        name:
          - net-tools
          - build-essential
          - wget
          - zip
          - unzip
          - fzf
          - curl
          - xclip
          - ripgrep
          - python3
          - python3-pip
          - tree
        state: present
      when: "'basics' in tools_to_install"

    - name: Install PyVim
      pip:
        name: pyvim
        executable: pip3
      when: "'basics' in tools_to_install"

    - name: Install ASDF
      git:
        repo: 'https://github.com/asdf-vm/asdf.git'
        dest: '{{ ansible_env.HOME }}/.asdf'
        version: 'v0.11.3'
        clone: yes
      when: "'asdf' in tools_to_install"

    - name: Ensure ASDF is in PATH
      lineinfile:
        path: ~/.profile
        line: 'export PATH="$HOME/.asdf/bin:$HOME/.asdf/shims:$PATH"'
        state: present
      when: "'asdf' in tools_to_install"
      
    - name: Install Zsh
      apt:
        name: zsh
        state: present
      when: "'zsh' in tools_to_install"

    - name: Set Zsh as default shell
      command: chsh -s /bin/zsh
      when: "'zsh' in tools_to_install"
      args:
        creates: /bin/zsh

    - name: Check if Oh My Zsh is already installed
      stat:
        path: "{{ ansible_env.HOME }}/.oh-my-zsh"
      register: zsh_install_check
      when: "'zsh' in tools_to_install"

    - name: Remove existing Oh My Zsh directory if exists
      file:
        path: "{{ ansible_env.HOME }}/.oh-my-zsh"
        state: absent
      when: "'zsh' in tools_to_install and zsh_install_check.stat.exists"

    - name: Install Oh My Zsh
      become_user: "{{ ansible_user }}"
      shell: |
        export RUNZSH=no
        curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh
      when: "'zsh' in tools_to_install and not zsh_install_check.stat.exists"

    - name: Install i3 window manager
      apt:
        name: i3
        state: present
      when: "'i3' in tools_to_install"

    - name: Install Rofi
      apt:
        name: rofi
        state: present
      when: "'rofi' in tools_to_install"

    - name: Install Polybar
      apt:
        name: polybar
        state: present
      when: "'polybar' in tools_to_install"

    - name: Install Kitty terminal
      apt:
        name: kitty
        state: present
      when: "'kitty' in tools_to_install"

    - name: Install Tmux
      apt:
        name: tmux
        state: present
      when: "'tmux' in tools_to_install"

    - name: Install Neovim
      block:
        - name: Download Neovim
          get_url:
            url: https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz
            dest: /tmp/nvim-linux64.tar.gz

        - name: Extract Neovim
          unarchive:
            src: /tmp/nvim-linux64.tar.gz
            dest: /opt
            remote_src: yes

        - name: Clean up Neovim archive
          file:
            path: /tmp/nvim-linux64.tar.gz
            state: absent
      when: "'neovim' in tools_to_install"

    - name: Install Timewarrior and Taskwarrior
      apt:
        name:
          - timewarrior
          - taskwarrior
        state: present
      when: "'timewarrior' in tools_to_install"

    - name: Ensure dotfile directories exist
      file:
        path: "{{ lookup('env', 'HOME') }}/{{ item.dest | dirname }}"
        state: directory
        mode: '0755'
      loop:
        - { dest: ".bashrc" }
        - { dest: ".zshrc" }
        - { dest: ".oh-my-zsh/themes/cyberpunk.zsh-theme" }
        - { dest: ".config/i3/config" }
        - { dest: ".config/kitty/kitty.conf" }
        - { dest: ".config/polybar/config" }
        - { dest: ".config/rofi/config.rasi" }
        - { dest: ".config/tmux/tmux.conf" }
        - { dest: ".taskrc" }
        - { dest: ".config/nvim" }
      when: "'dotfiles' in tools_to_install"

    - name: Symlink dotfiles
      ansible.builtin.file:
        src: "{{ playbook_dir }}/dotfiles/{{ item.src }}"
        dest: "{{ lookup('env', 'HOME') }}/{{ item.dest }}"
        state: link
        force: yes  # Overwrite existing files or directories
      loop:
        - { src: "bash/.bashrc", dest: ".bashrc" }
        - { src: "zsh/.zshrc", dest: ".zshrc" }
        - { src: "zsh/cyberpunk.zsh-theme", dest: ".oh-my-zsh/themes/cyberpunk.zsh-theme" }
        - { src: "i3/config", dest: ".config/i3/config" }
        - { src: "kitty/kitty.conf", dest: ".config/kitty/kitty.conf" }
        - { src: "polybar/config", dest: ".config/polybar/config" }
        - { src: "rofi/config.rasi", dest: ".config/rofi/config.rasi" }
        - { src: "tmux/tmux.conf", dest: ".config/tmux/tmux.conf" }
        - { src: "timewarrior/.taskrc", dest: ".taskrc" }
        - { src: "nvim", dest: ".config/nvim" }
      when: "'dotfiles' in tools_to_install"

